version: '3.8'

services:
  clickhouse:
    build: .
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: uldanabanana
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./training_data.csv:/var/lib/clickhouse/user_files/training_data.csv
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
